sudo: false
language: node_js
cache:
  directories:
    - ~/.yarn
    - ~/.nvm
notifications:
  email: false
node_js:
  - "6"
install:
  - npm -g install yarn
  - yarn
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
